config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :ratings
  resources :requests
  devise_for :users
  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'edit_user_registration', to: 'users/registrations#edit'
  end

  match 'accept_request', to: 'requests#accept_request', via: :post
  match 'cancel_request', to: 'requests#cancel_request', via: :post
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :ratings

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy, :accept_request, :cancel_request]


  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.where(user_other_id: nil)
    @user_posted_requests = Request.where(user_id: current_user.id)
    @user_accepted_requests = Request.where(user_other_id: current_user.id)
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    if @request.user_other_id.present?
      @other_user = User.find(@request.user_other_id)
    else
      @other_user = nil
    end
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id if current_user
    @request.poster_name = current_user.first_name+' '+ current_user.last_name
    if (@request.start_time) < DateTime.now
      respond_to do |format|
        format.html { redirect_to requests_url, notice: 'You cannot have the request time to happen in the past' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    else
      respond_to do |format|
        if @request.save
          format.html { redirect_to requests_url, notice: 'Request was successfully created.' }
          format.json { render :show, status: :created, location: @request }
        else
          format.html { render :new }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    if @request.user_other_id.present?
      respond_to do |format|
        format.html { redirect_to @request, notice: "You can\t edit request since someone already took the offer"}
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    else
      respond_to do |format|
        if @request.update(request_params)
          format.html { redirect_to @request, notice: 'Request was successfully updated.' }
          format.json { render :show, status: :ok, location: @request }
        else
          format.html { render :edit }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  def accept_request
    current_id = current_user.id
    UserMailer.accept_request_poster(current_user,@request).deliver_now
    UserMailer.accept_request_poster(User.find(@request.user_id), @request).deliver_now
    respond_to do |format|
      if current_id != @request.user_id && @request.update(user_other_id: current_id)
        format.html { redirect_to requests_path, notice: 'You accepted the request' }
        format.json { render :show, status: :ok, location: @request }
      else
        if current_id == @request.user_id
          format.html { redirect_to requests_path, notice: 'Cannot accept the request: You can\'t accept your own' }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        else
          format.html { redirect_to requests_path, notice: 'Cannot accept the request: update error. Ask system admin' }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def cancel_request
    current_id = current_user.id
    UserMailer.cancel_request_poster(User.find(@request.user_id), @request).deliver_now
    respond_to do |format|
      if current_id != @request.user_id && @request.update(user_other_id: nil)
        format.html { redirect_to requests_path, notice: 'You canceled the request' }
        format.json { render :show, status: :ok, location: @request }
      else
        if current_id == @request.user_id
          format.html { redirect_to requests_path, notice: 'Cannot accept the request: You can\'t accept your own' }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        else
          format.html { redirect_to requests_path, notice: 'Cannot accept the request: update error. Ask system admin' }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:poster_rating, :acceptor_rating, :poster_name, :acceptor_name, :food_description,
                                      :price, :end_time, :location, :exchange_method, :special_request, :start_time, :user_id, :user_other_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<br><br>
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<style>
   table {
   font-family: arial, sans-serif;
   border-collapse: collapse;
   width: 70%;
   }
   td, th {
   border: 1px solid #dddddd;
   text-align: left;
   padding: 8px;
   }
</style>


  <table>

    <div class="field">
      <tr>
      <td class="required"><%= f.label :price, "Offer Price" %></td>
      <td><%= f.number_field :price, :step => 0.01, :min =>0, :placeholder => 'eg) 2.55', :precision =>2, :required => true %></td>
      </tr>
    </tr>
    </div>

  <div class="field">
    <tr>
    <td class="required"><%= f.label :food_description %></td>
    <td><%= f.text_area :food_description, :placeholder => 'eg) Broccoli Mac and Cheese', :required => true %></td>
    </tr>
  </div>

  <div class="field">
    <tr>
    <td class="required"><%= f.label :start_time %> (Must be after current time)</td>
    <td><%= f.datetime_select :start_time, :ampm =>true, default: DateTime.now , min: Time.now%></td>
    </tr>
  </div>

    <div class="field">
      <tr>
      <td class="required"><%= f.label :end_time %> (Must be at least 5 minutes after start time)</td>
      <td><%= f.datetime_select :end_time, :ampm =>true, default: (DateTime.now+10.minute), max: Time.now + 14400%></td>
      </tr>
    </div>

  <div class="field">
    <tr>
    <td class="required"><%= f.label :location, "Dropoff Location" %></td>
    <td><%= f.select :location,[['BD','BD'], ['Law Cafe','Law Cafe'],['Village','Village'],['Holmes Lounge','Holmes Lounge'],['Stanley\'s', 'Stanley\'s'], ['DUC','DUC'], ['Subway','Subway']], :required => true %></td>
    </tr>
  </div>

  <div class="field">
    <tr>
    <td><%= f.label :special_request %></td>
    <td><%= f.text_area :special_request, :placeholder => 'eg) Extra napkins' %></td>
     </tr>
  </div>
</table>

  <div class="actions">
    <%= f.submit :id=>"submit"  %> <span name="fill">Fill all required fields</span>
  </div>
<% end %>

app/views/requests/edit.html.erb
<br><br>
<h1>Editing Request</h1>
<% if @request.user_other_id.present? %>
    <p style="color: red">You won't be able to edit this since a user has accepted the offer</p>
<% end %>
<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>
<div class="transparent-background">
<br>
<h1 style="text-align:center">Requests</h1>
<br>
<style>
  table, th {
    border-bottom: 2px solid;
    padding: 10px;
    overflow: hidden;
    white-space: nowrap;
    table-layout: fixed;
    text-overflow: ellipsis;
    width: 100%;
  }
  td {
    border-bottom: 1px solid;
    padding: 10px;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }
  .button {
    background-color: #4CB9BC;
    border: none;
    color: white;
    padding: 16px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin-left: 4px ;
    cursor: pointer;
  }
</style>
<a class="button" href="/requests/new" style="text-decoration:none; color:white; float:right">New Request</a>
<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'Requests')" id="defaultOpen">All Requests</button>
  <button class="tablinks" onclick="openTab(event, 'Posts')">My Requests</button>
  <button class="tablinks" onclick="openTab(event, 'Accepted')">Requests I've Accepted</button>
</div>

<div id="Requests" class="tabcontent">
  <table>
    <thead>
    <tr>
      <th>Rating</th>
      <th>Food Description</th>
      <th>Price</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Location</th>
    </tr>
    </thead>

    <tbody>
    <% @requests.each do |request| %>
        <% if (request.user_id == current_user.id || request.user_other_id == nil) && request.end_time - 300 > Time.now %>
            <% if request.user_id == current_user.id %>
                <tr class="highlight" bgcolor="#ccc" text-color="white">
            <%else%>
                <tr class="everyother">
            <%end%>
            <td onclick="location.href='<%= url_for(request) %>';">
              <% if request.user.accum_poster_rating.nil? %>
                  No Ratings
              <% else %>
                  <%= request.user.accum_poster_rating %>
              <% end %>

              <div onmousemove="movePopup(event)" class="popup">Click to expand</div></td>
            <td onclick="location.href='<%= url_for(request) %>';" style="max-width:200px;text-overflow:ellipsis"><%= request.food_description %></td>
            <td onclick="location.href='<%= url_for(request) %>';">$<%= number_with_precision(request.price, :precision => 2) %></td>
            <td onclick="location.href='<%= url_for(request) %>';"><%= request.start_time.strftime("%B %d, %Y") %></td>
            <td onclick="location.href='<%= url_for(request) %>';"><%= request.start_time.strftime('%I:%M %p') %></td>
            <td onclick="location.href='<%= url_for(request) %>';"><%= request.end_time.strftime('%I:%M %p') %></td>
            <td onclick="location.href='<%= url_for(request) %>';"><%= request.location %></td>
            </tr>
        <%end%>
    <% end %>
    </tbody>

  </table>
  <br>
  <span>Note: Gray rows are your own requests</span>
</div>


<div id="Posts" class="tabcontent">
  <table>
    <thead>
    <tr>
      <th>Status</th>
      <th>Food Description</th>
      <th>Price</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Location</th>
      <th colspan="3" style="text-align:center">View</th>
    </tr>
    </thead>

    <tbody>
    <% @user_posted_requests.each do |request| %>
        <tr class="everyother">
          <td onclick="location.href='<%= url_for(request) %>';">
            <% if request.user_other_id==nil && Time.now > request.end_time %>
                Expired
            <% elsif request.user_other_id!=nil && Time.now > request.end_time %>
                Completed
            <% elsif request.user_other_id==nil && Time.now < request.end_time %>
                Not Accepted
            <% elsif request.user_other_id!=nil && Time.now < request.end_time %>
                Accepted
            <% end %>
            <div class="popup">Click to expand</div>
          </td>
          <td onclick="location.href='<%= url_for(request) %>';" style="max-width:100px;text-overflow:ellipsis"><%= request.food_description %></td>
          <td onclick="location.href='<%= url_for(request) %>';">$<%= number_with_precision(request.price, :precision => 2) %></td>
          <td onclick="location.href='<%= url_for(request) %>';"><%= request.start_time.strftime("%B %d, %Y") %></td>
          <td onclick="location.href='<%= url_for(request) %>';"><%= request.start_time.strftime('%I:%M %p') %></td>
          <td onclick="location.href='<%= url_for(request) %>';"><%= request.end_time.strftime('%I:%M %p') %></td>
          <td onclick="location.href='<%= url_for(request) %>';"><%= request.location %></td>
          <% if request.user_other_id == nil && request.end_time > Time.now || request.start_time > Time.now-300 && request.user_other_id != nil %>
              <td><%= link_to 'Edit', edit_request_path(request) %></td>
              <td colspan="2"><%= link_to 'Delete', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% elsif request.user_other_id != nil && Time.now < request.start_time - 300 %>
              <td><%= link_to 'Edit', edit_request_path(request) %></td>
              <td><%= link_to 'Cancel', request %></td>
              <td><%= link_to 'Delete', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%elsif request.user_other_id != nil && Time.now > request.start_time && request.poster_rating == 0 %>
              <td colspan="3"><%= link_to 'Rate', new_rating_path(id: request.id, user_id: request.user_id)%></td>
          <%else%>
              <td colspan="3" onclick="location.href='<%= url_for(request) %>';"></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br>

</div>

<div id="Accepted" class="tabcontent">
  <table>
    <thead>
    <tr>
      <th>Poster Rating</th>
      <th>Food Description</th>
      <th>Price</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Location</th>
      <th>View</th>
    </tr>
    </thead>

    <tbody>
    <% @user_accepted_requests.each do |request| %>
        <tr class="everyother">
          <td onclick="location.href='<%= url_for(request) %>';">
            <% if User.find(request.user_other_id).accum_poster_rating.nil? %>
                No Ratings
            <% else %>
                <%= User.find(request.user_other_id).accum_poster_rating %>
            <% end %>
            <div class="popup">Click to expand</div></td>
          <td onclick="location.href='<%= url_for(request) %>';" style="width:50px;text-overflow:ellipsis"><%= request.food_description %></td>
          <td onclick="location.href='<%= url_for(request) %>';">$<%= number_with_precision(request.price, :precision => 2) %></td>
          <td onclick="location.href='<%= url_for(request) %>';"><%= request.start_time.strftime("%B %d, %Y") %></td>
          <td onclick="location.href='<%= url_for(request) %>';"><%= request.start_time.strftime('%I:%M %p') %></td>
          <td onclick="location.href='<%= url_for(request) %>';"><%= request.end_time.strftime('%I:%M %p') %></td>
          <td onclick="location.href='<%= url_for(request) %>';"><%= request.location %></td>
          <% if request.start_time > Time.now %>
              <td><%= link_to 'Cancel', cancel_request_path(id: request.id), method: :post, data: { confirm: 'Are you sure you want to cancel?'} %></td>
          <% elsif request.acceptor_rating == false %>
              <td><%= link_to 'Rate', new_rating_path(id: request.id, user_id: request.user_id)%></td>
          <%else%>
          <td></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br>
</div>

</div>
<script>
    //        var mouseX;
    //        var mouseY;
    //        $(document).mousemove( function(e) {
    //          mouseX = e.pageX;
    //          mouseY = e.pageY;
    //        });
    $(document).ready(function(){
        $('.highlight').hover(function() {
//                $(this).find('.popup').css({'left':mouseX, 'top':mouseY});
            $(this).find('.popup').show();
        }, function() {
            $(this).find('.popup').hide();
        })
    });
    function openTab(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }

    // Get the element with id="defaultOpen" and click on it
    document.getElementById("defaultOpen").click();
</script>

app/views/requests/new.html.erb
<div class="transparent-background">
  <br>
  <h1>New Request</h1>
  <%= render 'form', request: @request %>

  <%= link_to 'Back', requests_path %>
</div>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 31%;
  }
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
</style>
<br><br>
<table>

  <%if current_user.id == @request.user_id %>
      <h1>Showing Your Request</h1>
      <%if @request.user_other_id != nil %>
          <p>
            <tr>
              <td><strong>Rating:</strong></td>
              <td><%= User.find(@request.user_other_id).accum_acceptor_rating %></td>
            </tr>
          </p>
          <p>
            <tr>
              <td><strong>User:</strong></td>
              <td><%= @request.acceptor_name %></td>
            </tr>
          </p>
      <%else%>
          <p>
            <tr>
              <td><strong>Rating:</strong></td>
              <td>Has not been accepted yet</td>
            </tr>
          </p>
          <p>
            <tr>
              <td><strong>User:</strong></td>
              <td>Has not been accepted yet</td>
            </tr>
          </p>
      <%end%>
  <%else%>
      <h1>Showing <%= @request.poster_name %>'s Request</h1>
      <p>
        <tr>
          <td><strong>Rating:</strong></td>
          <td><%= User.find(@request.user_id).accum_poster_rating %></td>
        </tr>
      </p>
      <p>
        <tr>
          <td><strong>User:</strong></td>
          <td><%= @request.poster_name %></td>
        </tr>
      </p>
  <%end%>

  <p>
    <tr>
      <td><strong>Price:</strong></td>
      <td>$<%= number_with_precision(@request.price, :precision => 2) %></td>
    </tr>
  </p>

  <p>
    <tr>
      <td><strong>Food description:</strong></td>
      <td><%= @request.food_description %></td>
    </tr>
  </p>

  <p>
    <tr>
      <td><strong>Date:</strong></td>
      <td><%= @request.start_time.strftime("%B %d, %Y") %></td>
    </tr>
  </p>

  <p>
    <tr>
      <td><strong>Deliver After:</strong></td>
      <td><%= @request.start_time.strftime('%I:%M:%S %p') %></td>
    </tr>
  </p>
  <p>
    <tr>
      <td><strong>Deliver By:</strong></td>
      <td><%= @request.end_time.strftime('%I:%M:%S %p') %></td>
    </tr>
  </p>

  <p>
    <tr>
      <td><strong>Dropoff Location:</strong></td>
      <td><%= @request.location %></td>
    </tr>
  </p>

  <p>
    <tr>
      <td><strong>Special request:</strong></td>
      <td><%= @request.special_request %></td>
    </tr>
  </p>
</table>

<%if current_user.id == @request.user_id %>
    <%if @request.user_other_id == nil %>
        <%if @request.end_time - 300 > Time.now %>
            <%= link_to 'Edit', edit_request_path(@request) %> |
            <%= link_to 'Delete', request_path, method: :delete, data: { confirm: 'Are you sure?' } %> |
            <%= link_to 'Back', requests_path %>
        <%else%>
            <%= link_to 'Back', requests_path %>
        <%end%>
    <%else%>
        <%if @request.start_time - 300 > Time.now %>
            <%= link_to 'Edit', edit_request_path(@request) %> |
            <%= link_to 'Cancel', cancel_request_path(id: @request.id), method: :post, data: { confirm: 'Are you sure you want to cancel?'} %> |
            <%= link_to 'Delete', request_path, method: :delete, data: { confirm: 'Are you sure?' } %> |
            <%= link_to 'Back', requests_path %>
        <% elsif Time.now < @request.start_time && Time.now > @request.start_time - 300 %>
            <%= link_to 'Back', requests_path %>
        <% elsif Time.now > @request.start_time && @request.acceptor_rating == nil %>
            <%= link_to 'Rate', new_rating_path(id: request.id, user_id: request.user_id)%>
            <%= link_to 'Back', requests_path %>
        <% else %>
            <%= link_to 'Back', requests_path %>
        <%end%>
    <%end%>
<%elsif current_user.id == @request.user_other_id %>
    <%if Time.now < @request.start_time - 300 %>
        <%= link_to 'Cancel', cancel_request_path(id: @request.id), method: :post, data: { confirm: 'Are you sure you want to cancel?'} %>
        <%= link_to 'Back', requests_path %>
    <%elsif Time.now < @request.start_time %>
        <%= link_to 'Back', requests_path %>
    <%elsif Time.now > @request.start_time && @request.poster_rating == nil %>
        <%= link_to 'Rate', new_rating_path(id: request.id, user_id: request.user_id)%>
        <%= link_to 'Back', requests_path %>
    <% else %>
        <%= link_to 'Back', requests_path %>
    <%end%>
<%else%>
    <%if Time.now < @request.end_time - 300 && @request.user_other_id == nil %>
        <%= link_to 'Accept', accept_request_path(id: @request.id), method: :post %> |
        <%= link_to 'Back', requests_path %>
    <%else%>
        <%= link_to 'Back', requests_path %>
    <%end%>
<%end%>